# Generated by Django 4.0 on 2022-04-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('blog_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('publish_date', models.DateField()),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='blog_images')),
            ],
        ),
    ]
