# Generated by Django 3.2.11 on 2022-03-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='img',
            field=models.ImageField(upload_to='blog_images'),
        ),
    ]
