# Generated by Django 3.2.11 on 2022-04-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogs_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='excerpt',
            field=models.TextField(default='Hello added default value as excerpt'),
            preserve_default=False,
        ),
    ]
