# Generated by Django 4.0 on 2022-05-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogs_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='img',
            field=models.ImageField(upload_to='static/images/blog_images'),
        ),
    ]
