# Generated by Django 4.0 on 2022-01-27 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('height', models.DecimalField(decimal_places=1, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('fitness_goal', models.CharField(max_length=20)),
                ('curr_exercise', models.PositiveIntegerField()),
                ('food_pref', models.CharField(max_length=10)),
                ('health_issues', models.CharField(max_length=100)),
            ],
        ),
    ]
