# Generated by Django 3.2.11 on 2022-01-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='health_issues',
        ),
        migrations.AddField(
            model_name='profile',
            name='diabetes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='kidney',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='lactose',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='pcos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='thyroid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='curr_exercise',
            field=models.CharField(max_length=50),
        ),
    ]
