# Generated by Django 4.0 on 2022-02-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220131_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='start_wt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
