# Generated by Django 4.0 on 2022-02-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_start_wt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='target_wt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
