# Generated by Django 4.0 on 2022-03-10 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0004_profile_target_wt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('diet_calories', models.PositiveBigIntegerField()),
                ('plan_exists', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('like_milk', models.BooleanField(default=True)),
                ('like_seeds_nuts', models.BooleanField(default=True)),
                ('like_sweets', models.BooleanField(default=True)),
                ('like_fruits', models.BooleanField(default=True)),
                ('like_salads', models.BooleanField(default=True)),
            ],
        ),
    ]
