# Generated by Django 3.2.11 on 2022-03-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='like_north',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='like_south',
            field=models.BooleanField(default=True),
        ),
    ]
