# Generated by Django 4.0 on 2022-03-26 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0006_auto_20220316_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('wo_exists', models.BooleanField(default=False)),
                ('wo_calories', models.PositiveBigIntegerField()),
                ('time', models.CharField(max_length=500)),
                ('wo_type', models.CharField(max_length=500)),
                ('wo_plan', models.TextField()),
            ],
        ),
    ]
