# Generated by Django 4.0 on 2022-03-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=71, max_digits=5),
            preserve_default=False,
        ),
    ]
