# Generated by Django 3.2.11 on 2022-04-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_breakfast_dinner_lunch_snacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='bf_fruits_1',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='bf_fruits_2',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='bf_fruits_3',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='bf_main_1',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='bf_main_2',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='bf_main_3',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='bf_milk_1',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='bf_milk_2',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='bf_milk_3',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='bf_nuts_1',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='bf_nuts_2',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='bf_nuts_3',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='bf_pp_1',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='bf_pp_2',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='bf_pp_3',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='d_main_1',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='d_main_2',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='d_main_3',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='d_pp_1',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='d_pp_2',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='d_pp_3',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='d_salad_1',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='d_salad_2',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='d_salad_3',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='d_side_1',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='d_side_2',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='d_side_3',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='l_main_1',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='l_main_2',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='l_main_3',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='l_pp_1',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='l_pp_2',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='l_pp_3',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='l_salad_1',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='l_salad_2',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='l_salad_3',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='l_side_1',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='l_side_2',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='l_side_3',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='s_fruit_1',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='s_fruit_2',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='s_fruit_3',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='s_main_1',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='s_main_2',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='s_main_3',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='s_sweet_1',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='s_sweet_2',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='snacks',
            name='s_sweet_3',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
