# Generated by Django 3.2.11 on 2022-04-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220415_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='bf_carbs',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diet',
            name='bf_fats',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diet',
            name='bf_protein',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diet',
            name='ld_carbs',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diet',
            name='ld_fats',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diet',
            name='ld_protein',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diet',
            name='snacks_carbs',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diet',
            name='snacks_fats',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diet',
            name='snacks_protein',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
    ]
