# Generated by Django 3.2.11 on 2022-04-16 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220416_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='snacks_carbs',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='snacks_fats',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='snacks_protein',
        ),
    ]
