# Generated by Django 3.2.11 on 2022-04-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20220416_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='snack_calories',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
    ]
