# Generated by Django 3.2.11 on 2022-04-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_diet_snack_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast',
            name='choices',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinner',
            name='choices',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lunch',
            name='choices',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snacks',
            name='choices',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
