# Generated by Django 4.0 on 2022-05-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220416_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='sug_wo_cal',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='sug_wo_categories',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='sug_wo_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='sug_wo_time',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='workout',
            name='wo_type',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
