# Generated by Django 4.0 on 2022-05-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_workout_sug_wo_cal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='sug_wo_cal',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='sug_wo_categories',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='sug_wo_name',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='sug_wo_time',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='workout',
            name='wo_type',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
